// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYdOUVHMp7PXS1CJHDOJTRpaDNhYARM14',
    appId: '1:953037226181:web:7b9055fdd56e2abaf5f0ac',
    messagingSenderId: '953037226181',
    projectId: 'colab-match',
    authDomain: 'colab-match.firebaseapp.com',
    storageBucket: 'colab-match.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgxmatPB0c6CZsArgQHNvFuhkJ_wI8JYI',
    appId: '1:953037226181:android:1cddfa5c3a5debfbf5f0ac',
    messagingSenderId: '953037226181',
    projectId: 'colab-match',
    storageBucket: 'colab-match.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEP89fFv7aJ5_wh_MspUtAopljujaqCWo',
    appId: '1:953037226181:ios:de2fa08bba6746c8f5f0ac',
    messagingSenderId: '953037226181',
    projectId: 'colab-match',
    storageBucket: 'colab-match.firebasestorage.app',
    iosBundleId: 'com.eunice.colabMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEP89fFv7aJ5_wh_MspUtAopljujaqCWo',
    appId: '1:953037226181:ios:de2fa08bba6746c8f5f0ac',
    messagingSenderId: '953037226181',
    projectId: 'colab-match',
    storageBucket: 'colab-match.firebasestorage.app',
    iosBundleId: 'com.eunice.colabMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYdOUVHMp7PXS1CJHDOJTRpaDNhYARM14',
    appId: '1:953037226181:web:b97d4eea37bfe0abf5f0ac',
    messagingSenderId: '953037226181',
    projectId: 'colab-match',
    authDomain: 'colab-match.firebaseapp.com',
    storageBucket: 'colab-match.firebasestorage.app',
  );
}
